export const listData = [
  {
    id: 1,
    title: "A Great Apartment Next to the Beach ",
    img: "Kitchen.jpg",
    bedrooms: 2,
    bathrooms: 1,
    price: 1000,
    address: "456 Park Avenue, London",
    latitude: 51.5074,
    longitude: -0.1278,
  },

  {
    id: 2,
    title: "A Great Apartment Next to the Beach ",
    img: "Kitchen.jpg",
    bedrooms: 2,
    bathrooms: 1,
    price: 1000,
    address: "456 Park Avenue, London",
    latitude: 51.5074,
    longitude: -0.1278,
  },

  {
    id: 3,
    title: "A Great Apartment Next to the Beach ",
    img: "Kitchen.jpg",
    bedrooms: 2,
    bathrooms: 1,
    price: 1000,
    address: "456 Park Avenue, London",
    latitude: 51.5074,
    longitude: -0.1278,
  },

  {
    id: 4,
    title: "A Great Apartment Next to the Beach ",
    img: "Kitchen.jpg",
    bedrooms: 2,
    bathrooms: 1,
    price: 1000,
    address: "456 Park Avenue, London",
    latitude: 51.5074,
    longitude: -0.1278,
  },

  {
    id: 5,
    title: "A Great Apartment Next to the Beach ",
    img: "Kitchen.jpg",
    bedrooms: 2,
    bathrooms: 1,
    price: 1000,
    address: "456 Park Avenue, London",
    latitude: 51.5074,
    longitude: -0.1278,
  },

  {
    id: 6,
    title: "A Great Apartment Next to the Beach ",
    img: "Kitchen.jpg",
    bedrooms: 2,
    bathrooms: 1,
    price: 1000,
    address: "456 Park Avenue, London",
    latitude: 51.5074,
    longitude: -0.1278,
  },

  {
    id: 7,
    title: "A Great Apartment Next to the Beach ",
    img: "Kitchen.jpg",
    bedrooms: 2,
    bathrooms: 1,
    price: 1000,
    address: "456 Park Avenue, London",
    latitude: 51.5074,
    longitude: -0.1278,
  },
];
